// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCINFICUeYEckgPYj7Zrn_u4JNyEhOB5QQ',
    appId: '1:1030937974870:web:763fe35c56d9844b9903f7',
    messagingSenderId: '1030937974870',
    projectId: 'citrusclassification',
    authDomain: 'citrusclassification.firebaseapp.com',
    storageBucket: 'citrusclassification.firebasestorage.app',
    measurementId: 'G-Z84EHMED6J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpBx7ddK9e2lfz3sgzN6F9K6-sAvL5lAI',
    appId: '1:1030937974870:android:de9f765f9ef0a9f79903f7',
    messagingSenderId: '1030937974870',
    projectId: 'citrusclassification',
    storageBucket: 'citrusclassification.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKp4NrEtqA1xbPEG8Z9EwlCkLoIH2l2EM',
    appId: '1:1030937974870:ios:de402f68531459a89903f7',
    messagingSenderId: '1030937974870',
    projectId: 'citrusclassification',
    storageBucket: 'citrusclassification.firebasestorage.app',
    iosBundleId: 'com.example.citrusclassification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCINFICUeYEckgPYj7Zrn_u4JNyEhOB5QQ',
    appId: '1:1030937974870:web:2373f5d9693cea579903f7',
    messagingSenderId: '1030937974870',
    projectId: 'citrusclassification',
    authDomain: 'citrusclassification.firebaseapp.com',
    storageBucket: 'citrusclassification.firebasestorage.app',
    measurementId: 'G-BLGGBEM49X',
  );
}
